import Head from 'next/head'
import Script from 'next/script'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <Script strategy="beforeInteractive" src="/script.js" />
      <Script
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: ` createChatBot(host = 'http://localhost:5005/webhooks/rest/webhook',
          botLogo = "/imgs/bot-logo2.png ",
          title = "Mental AI BOT ", welcomeMessage = "Hey, i am Mental AI Bot ",
          inactiveMsg = "Server is down, Please contact the developer to activate it ",
          theme="blue ")`}}>
      </Script>
      <div id="chat-container">

      </div>
    </div>
  )
}
